---
title: "Los Angeles Brewery Map"
date: "December 20, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r,message=FALSE}
library(leaflet)
library(dplyr)
brew <- read.csv("C:/Users/sec/GitHubRepos/DevelopingDataProducts/Project1/breweries.csv", 
                 header=TRUE)
brew <-  mutate(brew, 
                name = as.character(brew$name),
                siteHTML = paste0("<a href='http://www.",website,"'>",name,"</a>"))
```

#### Here is a listing of craft breweries in the Los Angeles/South Bay area. There are certainly more breweries than appear on this map. Hopefully they will be added soon. 

#### Clicking on a marker on the map will give the link to the brewery's website. Hopefully you find something interesting!

```{r}
myIcon <- makeIcon(
  iconUrl = "http://i.imgur.com/OBSjp4L.png",
  iconWidth = 35, iconHeight = 35*1.17,
  iconAnchorX = 35/2, iconAnchorY = 30
)
brew %>%
    leaflet() %>%
    addTiles() %>%
    addMarkers(lat=brew$lat, lng=brew$lng, 
               popup=brew$siteHTML, 
               icon=myIcon,
               clusterOptions = markerClusterOptions())

```

## Alphabetical List of Breweries on Map

```{r, comment=""}
library(knitr)
brew <- arrange(brew, name)
brewlist <- cbind(1:nrow(brew), brew$name)
kable(brewlist, col.names = c("", "Brewery Name"))
```